<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260904062920 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'The whole schema, on PostgreSQL.';
    }

    public function up(Schema $schema): void
    {
        $this->addSql(<<<'SQL'
                CREATE TABLE fixtures (
                  id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                  round_number SMALLINT NOT NULL,
                  leg SMALLINT NOT NULL,
                  kick_off_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
                  status VARCHAR(16) DEFAULT 'SCHEDULED' NOT NULL,
                  home_score SMALLINT DEFAULT 0 NOT NULL,
                  away_score SMALLINT DEFAULT 0 NOT NULL,
                  started_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
                  finished_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
                  created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
                  updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
                  season_id INT NOT NULL,
                  home_team_id INT NOT NULL,
                  away_team_id INT NOT NULL,
                  PRIMARY KEY (id)
                )
            SQL);
        $this->addSql('CREATE INDEX IDX_5CB9E5344EC001D1 ON fixtures (season_id)');
        $this->addSql('CREATE INDEX IDX_5CB9E5349C4C13F6 ON fixtures (home_team_id)');
        $this->addSql('CREATE INDEX IDX_5CB9E53445185D02 ON fixtures (away_team_id)');
        $this->addSql('CREATE INDEX idx_fixture_season_round ON fixtures (season_id, round_number)');
        $this->addSql('CREATE INDEX idx_fixture_season_status ON fixtures (season_id, status)');
        $this->addSql(<<<'SQL'
                CREATE UNIQUE INDEX uniq_fixture_season_direction ON fixtures (
                  season_id, home_team_id, away_team_id
                )
            SQL);
        $this->addSql('COMMENT ON COLUMN fixtures.kick_off_at IS \'UTC\'');
        $this->addSql('COMMENT ON COLUMN fixtures.started_at IS \'UTC\'');
        $this->addSql('COMMENT ON COLUMN fixtures.finished_at IS \'UTC\'');
        $this->addSql('COMMENT ON COLUMN fixtures.created_at IS \'UTC\'');
        $this->addSql('COMMENT ON COLUMN fixtures.updated_at IS \'UTC\'');
        $this->addSql(<<<'SQL'
                CREATE TABLE leagues (
                  id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                  name VARCHAR(150) NOT NULL,
                  slug VARCHAR(64) NOT NULL,
                  description TEXT NOT NULL,
                  created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
                  updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
                  organization_id INT NOT NULL,
                  PRIMARY KEY (id)
                )
            SQL);
        $this->addSql('CREATE INDEX IDX_85CE39E32C8A3DE ON leagues (organization_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_league_organization_slug ON leagues (organization_id, slug)');
        $this->addSql('COMMENT ON COLUMN leagues.created_at IS \'UTC\'');
        $this->addSql('COMMENT ON COLUMN leagues.updated_at IS \'UTC\'');
        $this->addSql(<<<'SQL'
                CREATE TABLE match_events (
                  id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                  type VARCHAR(16) NOT NULL,
                  minute SMALLINT NOT NULL,
                  created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
                  updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
                  fixture_id INT NOT NULL,
                  team_id INT NOT NULL,
                  player_id INT NOT NULL,
                  related_player_id INT DEFAULT NULL,
                  PRIMARY KEY (id)
                )
            SQL);
        $this->addSql('CREATE INDEX IDX_F2E8AE4BE524616D ON match_events (fixture_id)');
        $this->addSql('CREATE INDEX IDX_F2E8AE4B296CD8AE ON match_events (team_id)');
        $this->addSql('CREATE INDEX IDX_F2E8AE4B99E6F5DF ON match_events (player_id)');
        $this->addSql('CREATE INDEX IDX_F2E8AE4B3127A9C4 ON match_events (related_player_id)');
        $this->addSql('CREATE INDEX idx_event_fixture_type ON match_events (fixture_id, type)');
        $this->addSql('COMMENT ON COLUMN match_events.created_at IS \'UTC\'');
        $this->addSql('COMMENT ON COLUMN match_events.updated_at IS \'UTC\'');
        $this->addSql(<<<'SQL'
                CREATE TABLE organization_memberships (
                  id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                  role VARCHAR(10) NOT NULL,
                  created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
                  updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
                  organization_id INT NOT NULL,
                  user_id INT NOT NULL,
                  PRIMARY KEY (id)
                )
            SQL);
        $this->addSql('CREATE INDEX IDX_B606E30D32C8A3DE ON organization_memberships (organization_id)');
        $this->addSql('CREATE INDEX IDX_B606E30DA76ED395 ON organization_memberships (user_id)');
        $this->addSql(<<<'SQL'
                CREATE UNIQUE INDEX uniq_membership_organization_user ON organization_memberships (organization_id, user_id)
            SQL);
        $this->addSql('COMMENT ON COLUMN organization_memberships.created_at IS \'UTC\'');
        $this->addSql('COMMENT ON COLUMN organization_memberships.updated_at IS \'UTC\'');
        $this->addSql(<<<'SQL'
                CREATE TABLE organizations (
                  id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                  name VARCHAR(150) NOT NULL,
                  slug VARCHAR(64) NOT NULL,
                  created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
                  updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
                  created_by_id INT NOT NULL,
                  PRIMARY KEY (id)
                )
            SQL);
        $this->addSql('CREATE INDEX IDX_427C1C7FB03A8386 ON organizations (created_by_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_organization_slug ON organizations (slug)');
        $this->addSql('COMMENT ON COLUMN organizations.created_at IS \'UTC\'');
        $this->addSql('COMMENT ON COLUMN organizations.updated_at IS \'UTC\'');
        $this->addSql(<<<'SQL'
                CREATE TABLE players (
                  id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                  first_name VARCHAR(100) NOT NULL,
                  last_name VARCHAR(100) NOT NULL,
                  date_of_birth DATE DEFAULT NULL,
                  created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
                  updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
                  organization_id INT NOT NULL,
                  PRIMARY KEY (id)
                )
            SQL);
        $this->addSql('CREATE INDEX IDX_264E43A632C8A3DE ON players (organization_id)');
        $this->addSql('CREATE INDEX idx_player_organization_last_name ON players (organization_id, last_name)');
        $this->addSql('COMMENT ON COLUMN players.created_at IS \'UTC\'');
        $this->addSql('COMMENT ON COLUMN players.updated_at IS \'UTC\'');
        $this->addSql(<<<'SQL'
                CREATE TABLE refresh_tokens (
                  refresh_token VARCHAR(128) NOT NULL,
                  username VARCHAR(255) NOT NULL,
                  valid TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
                  id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                  PRIMARY KEY (id)
                )
            SQL);
        $this->addSql('CREATE UNIQUE INDEX UNIQ_9BACE7E1C74F2195 ON refresh_tokens (refresh_token)');
        $this->addSql(<<<'SQL'
                CREATE TABLE roster_entries (
                  id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                  shirt_number SMALLINT DEFAULT NULL,
                  position VARCHAR(16) DEFAULT NULL,
                  captain BOOLEAN NOT NULL,
                  created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
                  updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
                  season_team_id INT NOT NULL,
                  player_id INT NOT NULL,
                  PRIMARY KEY (id)
                )
            SQL);
        $this->addSql('CREATE INDEX IDX_3B1FDA87C1571F0 ON roster_entries (season_team_id)');
        $this->addSql('CREATE INDEX IDX_3B1FDA8799E6F5DF ON roster_entries (player_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_roster_squad_player ON roster_entries (season_team_id, player_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_roster_squad_shirt ON roster_entries (season_team_id, shirt_number)');
        $this->addSql('CREATE UNIQUE INDEX uniq_roster_one_captain ON roster_entries (season_team_id) WHERE captain');
        $this->addSql('COMMENT ON COLUMN roster_entries.created_at IS \'UTC\'');
        $this->addSql('COMMENT ON COLUMN roster_entries.updated_at IS \'UTC\'');
        $this->addSql(<<<'SQL'
                CREATE TABLE season_teams (
                  id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                  created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
                  updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
                  season_id INT NOT NULL,
                  team_id INT NOT NULL,
                  PRIMARY KEY (id)
                )
            SQL);
        $this->addSql('CREATE INDEX IDX_81F3D5874EC001D1 ON season_teams (season_id)');
        $this->addSql('CREATE INDEX IDX_81F3D587296CD8AE ON season_teams (team_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_season_team ON season_teams (season_id, team_id)');
        $this->addSql('COMMENT ON COLUMN season_teams.created_at IS \'UTC\'');
        $this->addSql('COMMENT ON COLUMN season_teams.updated_at IS \'UTC\'');
        $this->addSql(<<<'SQL'
                CREATE TABLE seasons (
                  id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                  name VARCHAR(32) NOT NULL,
                  start_date DATE NOT NULL,
                  end_date DATE DEFAULT NULL,
                  created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
                  updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
                  league_id INT NOT NULL,
                  PRIMARY KEY (id)
                )
            SQL);
        $this->addSql('CREATE INDEX IDX_B4F4301C58AFC4DE ON seasons (league_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_season_league_name ON seasons (league_id, name)');
        $this->addSql('COMMENT ON COLUMN seasons.created_at IS \'UTC\'');
        $this->addSql('COMMENT ON COLUMN seasons.updated_at IS \'UTC\'');
        $this->addSql(<<<'SQL'
                CREATE TABLE teams (
                  id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                  name VARCHAR(150) NOT NULL,
                  slug VARCHAR(64) NOT NULL,
                  short_name VARCHAR(32) NOT NULL,
                  created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
                  updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
                  organization_id INT NOT NULL,
                  PRIMARY KEY (id)
                )
            SQL);
        $this->addSql('CREATE INDEX IDX_96C2225832C8A3DE ON teams (organization_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_team_organization_slug ON teams (organization_id, slug)');
        $this->addSql('COMMENT ON COLUMN teams.created_at IS \'UTC\'');
        $this->addSql('COMMENT ON COLUMN teams.updated_at IS \'UTC\'');
        $this->addSql(<<<'SQL'
                CREATE TABLE users (
                  id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                  email VARCHAR(180) NOT NULL,
                  password VARCHAR(255) NOT NULL,
                  first_name VARCHAR(100) NOT NULL,
                  last_name VARCHAR(100) NOT NULL,
                  created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
                  updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
                  PRIMARY KEY (id)
                )
            SQL);
        $this->addSql('CREATE UNIQUE INDEX uniq_user_email ON users (email)');
        $this->addSql('COMMENT ON COLUMN users.created_at IS \'UTC\'');
        $this->addSql('COMMENT ON COLUMN users.updated_at IS \'UTC\'');
        $this->addSql(<<<'SQL'
                ALTER TABLE
                  fixtures
                ADD
                  CONSTRAINT FK_5CB9E5344EC001D1 FOREIGN KEY (season_id) REFERENCES seasons (id) ON DELETE CASCADE NOT DEFERRABLE
            SQL);
        $this->addSql(<<<'SQL'
                ALTER TABLE
                  fixtures
                ADD
                  CONSTRAINT FK_5CB9E5349C4C13F6 FOREIGN KEY (home_team_id) REFERENCES teams (id) ON DELETE CASCADE NOT DEFERRABLE
            SQL);
        $this->addSql(<<<'SQL'
                ALTER TABLE
                  fixtures
                ADD
                  CONSTRAINT FK_5CB9E53445185D02 FOREIGN KEY (away_team_id) REFERENCES teams (id) ON DELETE CASCADE NOT DEFERRABLE
            SQL);
        $this->addSql(<<<'SQL'
                ALTER TABLE
                  leagues
                ADD
                  CONSTRAINT FK_85CE39E32C8A3DE FOREIGN KEY (organization_id) REFERENCES organizations (id) ON DELETE CASCADE NOT DEFERRABLE
            SQL);
        $this->addSql(<<<'SQL'
                ALTER TABLE
                  match_events
                ADD
                  CONSTRAINT FK_F2E8AE4BE524616D FOREIGN KEY (fixture_id) REFERENCES fixtures (id) ON DELETE CASCADE NOT DEFERRABLE
            SQL);
        $this->addSql(<<<'SQL'
                ALTER TABLE
                  match_events
                ADD
                  CONSTRAINT FK_F2E8AE4B296CD8AE FOREIGN KEY (team_id) REFERENCES teams (id) ON DELETE RESTRICT NOT DEFERRABLE
            SQL);
        $this->addSql(<<<'SQL'
                ALTER TABLE
                  match_events
                ADD
                  CONSTRAINT FK_F2E8AE4B99E6F5DF FOREIGN KEY (player_id) REFERENCES players (id) ON DELETE RESTRICT NOT DEFERRABLE
            SQL);
        $this->addSql(<<<'SQL'
                ALTER TABLE
                  match_events
                ADD
                  CONSTRAINT FK_F2E8AE4B3127A9C4 FOREIGN KEY (related_player_id) REFERENCES players (id) ON DELETE RESTRICT NOT DEFERRABLE
            SQL);
        $this->addSql(<<<'SQL'
                ALTER TABLE
                  organization_memberships
                ADD
                  CONSTRAINT FK_B606E30D32C8A3DE FOREIGN KEY (organization_id) REFERENCES organizations (id) ON DELETE CASCADE NOT DEFERRABLE
            SQL);
        $this->addSql(<<<'SQL'
                ALTER TABLE
                  organization_memberships
                ADD
                  CONSTRAINT FK_B606E30DA76ED395 FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE NOT DEFERRABLE
            SQL);
        $this->addSql(<<<'SQL'
                ALTER TABLE
                  organizations
                ADD
                  CONSTRAINT FK_427C1C7FB03A8386 FOREIGN KEY (created_by_id) REFERENCES users (id) ON DELETE RESTRICT NOT DEFERRABLE
            SQL);
        $this->addSql(<<<'SQL'
                ALTER TABLE
                  players
                ADD
                  CONSTRAINT FK_264E43A632C8A3DE FOREIGN KEY (organization_id) REFERENCES organizations (id) ON DELETE CASCADE NOT DEFERRABLE
            SQL);
        $this->addSql(<<<'SQL'
                ALTER TABLE
                  roster_entries
                ADD
                  CONSTRAINT FK_3B1FDA87C1571F0 FOREIGN KEY (season_team_id) REFERENCES season_teams (id) ON DELETE CASCADE NOT DEFERRABLE
            SQL);
        $this->addSql(<<<'SQL'
                ALTER TABLE
                  roster_entries
                ADD
                  CONSTRAINT FK_3B1FDA8799E6F5DF FOREIGN KEY (player_id) REFERENCES players (id) ON DELETE CASCADE NOT DEFERRABLE
            SQL);
        $this->addSql(<<<'SQL'
                ALTER TABLE
                  season_teams
                ADD
                  CONSTRAINT FK_81F3D5874EC001D1 FOREIGN KEY (season_id) REFERENCES seasons (id) ON DELETE CASCADE NOT DEFERRABLE
            SQL);
        $this->addSql(<<<'SQL'
                ALTER TABLE
                  season_teams
                ADD
                  CONSTRAINT FK_81F3D587296CD8AE FOREIGN KEY (team_id) REFERENCES teams (id) ON DELETE CASCADE NOT DEFERRABLE
            SQL);
        $this->addSql(<<<'SQL'
                ALTER TABLE
                  seasons
                ADD
                  CONSTRAINT FK_B4F4301C58AFC4DE FOREIGN KEY (league_id) REFERENCES leagues (id) ON DELETE CASCADE NOT DEFERRABLE
            SQL);
        $this->addSql(<<<'SQL'
                ALTER TABLE
                  teams
                ADD
                  CONSTRAINT FK_96C2225832C8A3DE FOREIGN KEY (organization_id) REFERENCES organizations (id) ON DELETE CASCADE NOT DEFERRABLE
            SQL);
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE fixtures DROP CONSTRAINT FK_5CB9E5344EC001D1');
        $this->addSql('ALTER TABLE fixtures DROP CONSTRAINT FK_5CB9E5349C4C13F6');
        $this->addSql('ALTER TABLE fixtures DROP CONSTRAINT FK_5CB9E53445185D02');
        $this->addSql('ALTER TABLE leagues DROP CONSTRAINT FK_85CE39E32C8A3DE');
        $this->addSql('ALTER TABLE match_events DROP CONSTRAINT FK_F2E8AE4BE524616D');
        $this->addSql('ALTER TABLE match_events DROP CONSTRAINT FK_F2E8AE4B296CD8AE');
        $this->addSql('ALTER TABLE match_events DROP CONSTRAINT FK_F2E8AE4B99E6F5DF');
        $this->addSql('ALTER TABLE match_events DROP CONSTRAINT FK_F2E8AE4B3127A9C4');
        $this->addSql('ALTER TABLE organization_memberships DROP CONSTRAINT FK_B606E30D32C8A3DE');
        $this->addSql('ALTER TABLE organization_memberships DROP CONSTRAINT FK_B606E30DA76ED395');
        $this->addSql('ALTER TABLE organizations DROP CONSTRAINT FK_427C1C7FB03A8386');
        $this->addSql('ALTER TABLE players DROP CONSTRAINT FK_264E43A632C8A3DE');
        $this->addSql('ALTER TABLE roster_entries DROP CONSTRAINT FK_3B1FDA87C1571F0');
        $this->addSql('ALTER TABLE roster_entries DROP CONSTRAINT FK_3B1FDA8799E6F5DF');
        $this->addSql('ALTER TABLE season_teams DROP CONSTRAINT FK_81F3D5874EC001D1');
        $this->addSql('ALTER TABLE season_teams DROP CONSTRAINT FK_81F3D587296CD8AE');
        $this->addSql('ALTER TABLE seasons DROP CONSTRAINT FK_B4F4301C58AFC4DE');
        $this->addSql('ALTER TABLE teams DROP CONSTRAINT FK_96C2225832C8A3DE');
        $this->addSql('DROP TABLE fixtures');
        $this->addSql('DROP TABLE leagues');
        $this->addSql('DROP TABLE match_events');
        $this->addSql('DROP TABLE organization_memberships');
        $this->addSql('DROP TABLE organizations');
        $this->addSql('DROP TABLE players');
        $this->addSql('DROP TABLE refresh_tokens');
        $this->addSql('DROP TABLE roster_entries');
        $this->addSql('DROP TABLE season_teams');
        $this->addSql('DROP TABLE seasons');
        $this->addSql('DROP TABLE teams');
        $this->addSql('DROP TABLE users');
    }
}
