<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260904094000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return <<<'TEXT'
            Notifications, and the queue they arrive through.

            `messenger_messages` is here rather than being created on the fly because the
            transport DSN carries `auto_setup=0`. Left on, the transport issues a CREATE TABLE
            IF NOT EXISTS before its first use — convenient in development and wrong everywhere
            else: schema changes would happen outside migrations, at an unpredictable moment,
            from a worker process, against whatever privileges that process happens to have.

            The unique index on `dedupe_key` is the part that makes redelivery harmless. A
            queue promises at least once; this is what turns that into at most one notification.
            TEXT;
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE notifications (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, type VARCHAR(32) NOT NULL, title VARCHAR(160) NOT NULL, body VARCHAR(320) NOT NULL, link VARCHAR(255) NOT NULL, dedupe_key VARCHAR(191) NOT NULL, read_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, recipient_id INT NOT NULL, organization_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_6000B0D3E92F8F78 ON notifications (recipient_id)');
        $this->addSql('CREATE INDEX IDX_6000B0D332C8A3DE ON notifications (organization_id)');
        $this->addSql('CREATE INDEX idx_notification_recipient_read ON notifications (recipient_id, read_at, created_at)');
        $this->addSql('CREATE UNIQUE INDEX uniq_notification_dedupe ON notifications (dedupe_key)');
        $this->addSql('COMMENT ON COLUMN notifications.read_at IS \'UTC\'');
        $this->addSql('COMMENT ON COLUMN notifications.created_at IS \'UTC\'');
        $this->addSql('COMMENT ON COLUMN notifications.updated_at IS \'UTC\'');
        $this->addSql('CREATE TABLE messenger_messages (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, body TEXT NOT NULL, headers TEXT NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, available_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, delivered_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_75EA56E0FB7336F0E3BD61CE16BA31DBBF396750 ON messenger_messages (queue_name, available_at, delivered_at, id)');
        $this->addSql('ALTER TABLE notifications ADD CONSTRAINT FK_6000B0D3E92F8F78 FOREIGN KEY (recipient_id) REFERENCES users (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE notifications ADD CONSTRAINT FK_6000B0D332C8A3DE FOREIGN KEY (organization_id) REFERENCES organizations (id) ON DELETE CASCADE NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE notifications DROP CONSTRAINT FK_6000B0D3E92F8F78');
        $this->addSql('ALTER TABLE notifications DROP CONSTRAINT FK_6000B0D332C8A3DE');
        $this->addSql('DROP TABLE notifications');
        $this->addSql('DROP TABLE messenger_messages');
    }
}
